// js/state/pitchData.ts
import type { PitchRowData } from '../../types/state.js';

/**
 * The single source of truth for all pitch information in the application.
 * Each object contains:
 * - pitch: The display name for the pitch (e.g., "B♭/A♯7") - combined notation for accidentals, single for naturals.
 * - flatName: The flat enharmonic spelling (e.g., "B♭7") - same as pitch for naturals.
 * - sharpName: The sharp enharmonic spelling (e.g., "A♯7") - same as pitch for naturals.
 * - toneNote: The scientific pitch notation compatible with Tone.js (e.g., "Bb7").
 * - frequency: The frequency in Hz.
 * - column: The legend column ('A' or 'B') this pitch belongs to, corresponding to the dual-parity rank system.
 * - hex: The specific color code for this exact pitch.
 * - isAccidental: Boolean flag indicating if this is a black key (accidental note).
 */
export const fullRowData: PitchRowData[] = [
  { pitch: 'C8', flatName: 'C8', sharpName: 'C8', toneNote: 'C8', frequency: 4186.01, column: 'A', hex: '#fef1f5', isAccidental: false },
  { pitch: 'B7', flatName: 'B7', sharpName: 'B7', toneNote: 'B7', frequency: 3951.07, column: 'B', hex: '#fbf2fa', isAccidental: false },
  { pitch: 'B♭/A♯7', flatName: 'B♭7', sharpName: 'A♯7', toneNote: 'Bb7', frequency: 3729.31, column: 'A', hex: '#f6f3fd', isAccidental: true },
  { pitch: 'A7', flatName: 'A7', sharpName: 'A7', toneNote: 'A7', frequency: 3520.00, column: 'B', hex: '#f1f5ff', isAccidental: false },
  { pitch: 'A♭/G♯7', flatName: 'A♭7', sharpName: 'G♯7', toneNote: 'Ab7', frequency: 3322.44, column: 'A', hex: '#edf7fe', isAccidental: true },
  { pitch: 'G7', flatName: 'G7', sharpName: 'G7', toneNote: 'G7', frequency: 3135.96, column: 'B', hex: '#ebf8fa', isAccidental: false },
  { pitch: 'G♭/F♯7', flatName: 'G♭7', sharpName: 'F♯7', toneNote: 'Gb7', frequency: 2959.96, column: 'A', hex: '#ecf8f5', isAccidental: true },
  { pitch: 'F7', flatName: 'F7', sharpName: 'F7', toneNote: 'F7', frequency: 2793.83, column: 'B', hex: '#eff8f0', isAccidental: false },
  { pitch: 'E7', flatName: 'E7', sharpName: 'E7', toneNote: 'E7', frequency: 2637.02, column: 'A', hex: '#f4f7ec', isAccidental: false },
  { pitch: 'E♭/D♯7', flatName: 'E♭7', sharpName: 'D♯7', toneNote: 'Eb7', frequency: 2489.02, column: 'B', hex: '#f9f5eb', isAccidental: true },
  { pitch: 'D7', flatName: 'D7', sharpName: 'D7', toneNote: 'D7', frequency: 2349.32, column: 'A', hex: '#fdf3ec', isAccidental: false },
  { pitch: 'D♭/C♯7', flatName: 'D♭7', sharpName: 'C♯7', toneNote: 'Db7', frequency: 2217.46, column: 'B', hex: '#fef2f0', isAccidental: true },
  { pitch: 'C7', flatName: 'C7', sharpName: 'C7', toneNote: 'C7', frequency: 2093.00, column: 'A', hex: '#fef1f5', isAccidental: false },
  { pitch: 'B6', flatName: 'B6', sharpName: 'B6', toneNote: 'B6', frequency: 1975.53, column: 'B', hex: '#f0d1ec', isAccidental: false },
  { pitch: 'B♭/A♯6', flatName: 'B♭6', sharpName: 'A♯6', toneNote: 'Bb6', frequency: 1864.66, column: 'A', hex: '#e1d6f9', isAccidental: true },
  { pitch: 'A6', flatName: 'A6', sharpName: 'A6', toneNote: 'A6', frequency: 1760.00, column: 'B', hex: '#cfdcff', isAccidental: false },
  { pitch: 'A♭/G♯6', flatName: 'A♭6', sharpName: 'G♯6', toneNote: 'Ab6', frequency: 1661.22, column: 'A', hex: '#bfe2fb', isAccidental: true },
  { pitch: 'G6', flatName: 'G6', sharpName: 'G6', toneNote: 'G6', frequency: 1567.94, column: 'B', hex: '#b7e6ef', isAccidental: false },
  { pitch: 'G♭/F♯6', flatName: 'G♭6', sharpName: 'F♯6', toneNote: 'Gb6', frequency: 1479.98, column: 'A', hex: '#b9e8dd', isAccidental: true },
  { pitch: 'F6', flatName: 'F6', sharpName: 'F6', toneNote: 'F6', frequency: 1396.91, column: 'B', hex: '#c6e6cb', isAccidental: false },
  { pitch: 'E6', flatName: 'E6', sharpName: 'E6', toneNote: 'E6', frequency: 1318.51, column: 'A', hex: '#d8e2bd', isAccidental: false },
  { pitch: 'E♭/D♯6', flatName: 'E♭6', sharpName: 'D♯6', toneNote: 'Eb6', frequency: 1244.51, column: 'B', hex: '#e9dcb7', isAccidental: true },
  { pitch: 'D6', flatName: 'D6', sharpName: 'D6', toneNote: 'D6', frequency: 1174.66, column: 'A', hex: '#f6d5bc', isAccidental: false },
  { pitch: 'D♭/C♯6', flatName: 'D♭6', sharpName: 'C♯6', toneNote: 'Db6', frequency: 1108.73, column: 'B', hex: '#fcd1c9', isAccidental: true },
  { pitch: 'C6', flatName: 'C6', sharpName: 'C6', toneNote: 'C6', frequency: 1046.50, column: 'A', hex: '#facfdb', isAccidental: false },
  { pitch: 'B5', flatName: 'B5', sharpName: 'B5', toneNote: 'B5', frequency: 987.77, column: 'B', hex: '#e6b2e1', isAccidental: false },
  { pitch: 'B♭/A♯5', flatName: 'B♭5', sharpName: 'A♯5', toneNote: 'Bb5', frequency: 932.33, column: 'A', hex: '#cebaf6', isAccidental: true },
  { pitch: 'A5', flatName: 'A5', sharpName: 'A5', toneNote: 'A5', frequency: 880.00, column: 'B', hex: '#b0c4fe', isAccidental: false },
  { pitch: 'A♭/G♯5', flatName: 'A♭5', sharpName: 'G♯5', toneNote: 'Ab5', frequency: 830.61, column: 'A', hex: '#92cef8', isAccidental: true },
  { pitch: 'G5', flatName: 'G5', sharpName: 'G5', toneNote: 'G5', frequency: 783.99, column: 'B', hex: '#7fd5e5', isAccidental: false },
  { pitch: 'G♭/F♯5', flatName: 'G♭5', sharpName: 'F♯5', toneNote: 'Gb5', frequency: 739.99, column: 'A', hex: '#84d8c8', isAccidental: true },
  { pitch: 'F5', flatName: 'F5', sharpName: 'F5', toneNote: 'F5', frequency: 698.46, column: 'B', hex: '#9ed6a8', isAccidental: false },
  { pitch: 'E5', flatName: 'E5', sharpName: 'E5', toneNote: 'E5', frequency: 659.25, column: 'A', hex: '#bece8f', isAccidental: false },
  { pitch: 'E♭/D♯5', flatName: 'E♭5', sharpName: 'D♯5', toneNote: 'Eb5', frequency: 622.25, column: 'B', hex: '#dbc484', isAccidental: true },
  { pitch: 'D5', flatName: 'D5', sharpName: 'D5', toneNote: 'D5', frequency: 587.33, column: 'A', hex: '#f0b98d', isAccidental: false },
  { pitch: 'D♭/C♯5', flatName: 'D♭5', sharpName: 'C♯5', toneNote: 'Db5', frequency: 554.37, column: 'B', hex: '#f9b1a5', isAccidental: true },
  { pitch: 'C5', flatName: 'C5', sharpName: 'C5', toneNote: 'C5', frequency: 523.25, column: 'A', hex: '#f5afc3', isAccidental: false },
  { pitch: 'B4', flatName: 'B4', sharpName: 'B4', toneNote: 'B4', frequency: 493.88, column: 'B', hex: '#db8fd4', isAccidental: false },
  { pitch: 'B♭/A♯4', flatName: 'B♭4', sharpName: 'A♯4', toneNote: 'Bb4', frequency: 466.16, column: 'A', hex: '#ba9bf2', isAccidental: true },
  { pitch: 'A4', flatName: 'A4', sharpName: 'A4', toneNote: 'A4', frequency: 440.00, column: 'B', hex: '#8fa9ff', isAccidental: false },
  { pitch: 'A♭/G♯4', flatName: 'A♭4', sharpName: 'G♯4', toneNote: 'Ab4', frequency: 415.30, column: 'A', hex: '#58b8f6', isAccidental: true },
  { pitch: 'G4', flatName: 'G4', sharpName: 'G4', toneNote: 'G4', frequency: 392.00, column: 'B', hex: '#16c3da', isAccidental: false },
  { pitch: 'G♭/F♯4', flatName: 'G♭4', sharpName: 'F♯4', toneNote: 'Gb4', frequency: 369.99, column: 'A', hex: '#2dc8b1', isAccidental: true },
  { pitch: 'F4', flatName: 'F4', sharpName: 'F4', toneNote: 'F4', frequency: 349.23, column: 'B', hex: '#6ec482', isAccidental: false },
  { pitch: 'E4', flatName: 'E4', sharpName: 'E4', toneNote: 'E4', frequency: 329.63, column: 'A', hex: '#a4ba57', isAccidental: false },
  { pitch: 'E♭/D♯4', flatName: 'E♭4', sharpName: 'D♯4', toneNote: 'Eb4', frequency: 311.13, column: 'B', hex: '#cdaa42', isAccidental: true },
  { pitch: 'D4', flatName: 'D4', sharpName: 'D4', toneNote: 'D4', frequency: 293.66, column: 'A', hex: '#e89955', isAccidental: false },
  { pitch: 'D♭/C♯4', flatName: 'D♭4', sharpName: 'C♯4', toneNote: 'Db4', frequency: 277.18, column: 'B', hex: '#f48e7d', isAccidental: true },
  { pitch: 'C4', flatName: 'C4', sharpName: 'C4', toneNote: 'C4', frequency: 261.63, column: 'A', hex: '#ef8aab', isAccidental: false },
  { pitch: 'B3', flatName: 'B3', sharpName: 'B3', toneNote: 'B3', frequency: 246.94, column: 'B', hex: '#be7cb8', isAccidental: false },
  { pitch: 'B♭/A♯3', flatName: 'B♭3', sharpName: 'A♯3', toneNote: 'Bb3', frequency: 233.08, column: 'A', hex: '#a286d2', isAccidental: true },
  { pitch: 'A3', flatName: 'A3', sharpName: 'A3', toneNote: 'A3', frequency: 220.00, column: 'B', hex: '#7b93dd', isAccidental: false },
  { pitch: 'A♭/G♯3', flatName: 'A♭3', sharpName: 'G♯3', toneNote: 'Ab3', frequency: 207.65, column: 'A', hex: '#4c9fd6', isAccidental: true },
  { pitch: 'G3', flatName: 'G3', sharpName: 'G3', toneNote: 'G3', frequency: 196.00, column: 'B', hex: '#13a9bd', isAccidental: false },
  { pitch: 'G♭/F♯3', flatName: 'G♭3', sharpName: 'F♯3', toneNote: 'Gb3', frequency: 185.00, column: 'A', hex: '#27ad99', isAccidental: true },
  { pitch: 'F3', flatName: 'F3', sharpName: 'F3', toneNote: 'F3', frequency: 174.61, column: 'B', hex: '#5faa71', isAccidental: false },
  { pitch: 'E3', flatName: 'E3', sharpName: 'E3', toneNote: 'E3', frequency: 164.81, column: 'A', hex: '#8ea14b', isAccidental: false },
  { pitch: 'E♭/D♯3', flatName: 'E♭3', sharpName: 'D♯3', toneNote: 'Eb3', frequency: 155.56, column: 'B', hex: '#b29338', isAccidental: true },
  { pitch: 'D3', flatName: 'D3', sharpName: 'D3', toneNote: 'D3', frequency: 146.83, column: 'A', hex: '#ca8549', isAccidental: false },
  { pitch: 'D♭/C♯3', flatName: 'D♭3', sharpName: 'C♯3', toneNote: 'Db3', frequency: 138.59, column: 'B', hex: '#d47a6c', isAccidental: true },
  { pitch: 'C3', flatName: 'C3', sharpName: 'C3', toneNote: 'C3', frequency: 130.81, column: 'A', hex: '#cf7894', isAccidental: false },
  { pitch: 'B2', flatName: 'B2', sharpName: 'B2', toneNote: 'B2', frequency: 123.47, column: 'B', hex: '#a46b9f', isAccidental: false },
  { pitch: 'B♭/A♯2', flatName: 'B♭2', sharpName: 'A♯2', toneNote: 'Bb2', frequency: 116.54, column: 'A', hex: '#8b73b6', isAccidental: true },
  { pitch: 'A2', flatName: 'A2', sharpName: 'A2', toneNote: 'A2', frequency: 110.00, column: 'B', hex: '#6a7ebf', isAccidental: false },
  { pitch: 'A♭/G♯2', flatName: 'A♭2', sharpName: 'G♯2', toneNote: 'Ab2', frequency: 103.83, column: 'A', hex: '#4189b8', isAccidental: true },
  { pitch: 'G2', flatName: 'G2', sharpName: 'G2', toneNote: 'G2', frequency: 98.00, column: 'B', hex: '#1092a3', isAccidental: false },
  { pitch: 'G♭/F♯2', flatName: 'G♭2', sharpName: 'F♯2', toneNote: 'Gb2', frequency: 92.50, column: 'A', hex: '#219584', isAccidental: true },
  { pitch: 'F2', flatName: 'F2', sharpName: 'F2', toneNote: 'F2', frequency: 87.31, column: 'B', hex: '#519360', isAccidental: false },
  { pitch: 'E2', flatName: 'E2', sharpName: 'E2', toneNote: 'E2', frequency: 82.41, column: 'A', hex: '#7a8b40', isAccidental: false },
  { pitch: 'E♭/D♯2', flatName: 'E♭2', sharpName: 'D♯2', toneNote: 'Eb2', frequency: 77.78, column: 'B', hex: '#997f30', isAccidental: true },
  { pitch: 'D2', flatName: 'D2', sharpName: 'D2', toneNote: 'D2', frequency: 73.42, column: 'A', hex: '#ae723e', isAccidental: false },
  { pitch: 'D♭/C♯2', flatName: 'D♭2', sharpName: 'C♯2', toneNote: 'Db2', frequency: 69.30, column: 'B', hex: '#b7695d', isAccidental: true },
  { pitch: 'C2', flatName: 'C2', sharpName: 'C2', toneNote: 'C2', frequency: 65.41, column: 'A', hex: '#b3677f', isAccidental: false },
  { pitch: 'B1', flatName: 'B1', sharpName: 'B1', toneNote: 'B1', frequency: 61.74, column: 'B', hex: '#6f466b', isAccidental: false },
  { pitch: 'B♭/A♯1', flatName: 'B♭1', sharpName: 'A♯1', toneNote: 'Bb1', frequency: 58.27, column: 'A', hex: '#5d4c7b', isAccidental: true },
  { pitch: 'A1', flatName: 'A1', sharpName: 'A1', toneNote: 'A1', frequency: 55.00, column: 'B', hex: '#465482', isAccidental: false },
  { pitch: 'A♭/G♯1', flatName: 'A♭1', sharpName: 'G♯1', toneNote: 'Ab1', frequency: 51.91, column: 'A', hex: '#295c7d', isAccidental: true },
  { pitch: 'G1', flatName: 'G1', sharpName: 'G1', toneNote: 'G1', frequency: 49.00, column: 'B', hex: '#06626e', isAccidental: false },
  { pitch: 'G♭/F♯1', flatName: 'G♭1', sharpName: 'F♯1', toneNote: 'Gb1', frequency: 46.25, column: 'A', hex: '#126458', isAccidental: true },
  { pitch: 'F1', flatName: 'F1', sharpName: 'F1', toneNote: 'F1', frequency: 43.65, column: 'B', hex: '#34633f', isAccidental: false },
  { pitch: 'E1', flatName: 'E1', sharpName: 'E1', toneNote: 'E1', frequency: 41.20, column: 'A', hex: '#515d28', isAccidental: false },
  { pitch: 'E♭/D♯1', flatName: 'E♭1', sharpName: 'D♯1', toneNote: 'Eb1', frequency: 38.89, column: 'B', hex: '#67541d', isAccidental: true },
  { pitch: 'D1', flatName: 'D1', sharpName: 'D1', toneNote: 'D1', frequency: 36.71, column: 'A', hex: '#764c27', isAccidental: false },
  { pitch: 'D♭/C♯1', flatName: 'D♭1', sharpName: 'C♯1', toneNote: 'Db1', frequency: 34.65, column: 'B', hex: '#7c453d', isAccidental: true },
  { pitch: 'C1', flatName: 'C1', sharpName: 'C1', toneNote: 'C1', frequency: 32.70, column: 'A', hex: '#794455', isAccidental: false }
];
